### ISSUE TITLE
Localization of activity.md into Hindi

### ISSUE THREAD

**Issue by join2ashish** [mozilla/mozilla-club-activity-web-chef#10]
---

शीर्षक: वेब शेफ 
गिटहब : मोज़िला/मोज़िला-सभा-गतिविधि-वेब-शेफ 
तस्वीर: शेफ -मैन.जेपीजी 
दक्षताओं:
    - {लेबल: "खुला आचरण", प्रकार: "खुला-आचरण"}
### वेब शेफ

[मोज़िला] द्वारा बनाया गया (https://webmaker.org/mentor), और [ क्रिएटिव कॉमन्स ] से प्रेरित  (https://creativecommons.org/) और [ओपन के पी २ पी यू  स्कूल](https://p2pu.org/en/groups/teach-someone-something-with-open-content). 

शिक्षार्थियों एचटीएमएल टैग के साथ लेबल कागज को बक्से के अनुक्रम में करने के लिए दौड़ होगी, *_सबसे आम एचटीएमएल टैग से परिचित हो और कैसे एक वेब पेज संरचना करें यह सीखें *_.

१ - २ घंटे 
### तैयारी

गतिविधि को खुद से करें उससे सही रूप से परिचित होने के लिए 

[वेब शेफ रेसिपी को प्रिंट करें ](https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe) अपने शिक्षार्थियों के लिए ,और यदि आप के पास वेब का उपयोग नहीं हैं !

**[ पूर्व गतिविधि प्रश्नावली ] को पूरा करें(http://goo.gl/forms/J1fsuwZEgs)**, और [ उनके पूर्व गतिविधि प्रश्नावली ] अपने शिक्षार्थियों से पूरा करवाएं (http://goo.gl/forms/4DanIgrM9w). 

---

१ ५ <बी आर >मिनट 
### जोड़े में शिक्षण

सत्र को यह समझा कर शुरू करें की *_सबके पास कुछ सिखने को होता है और कुछ सीखने को *_और उसके साथ *_एक सबसे अच्छी ओपन वेब की यह बात है की ये दूसरों को शिछित करें के लिए बहुत आसान हैं *_

**क्या शिक्षार्थियों ने जोड़े में टीम बना ली ?** वे अपने साथी के साथ साझा कर सकते हैं एक सरल कौशल  के बारे में संक्षेप में सोचने के लिए शिक्षार्थियों को आमंत्रित करें . कुछ उदाहरणों में शामिल हैं: एक नया नृत्य , और आसानी से अपने जूते कैसे बांधें  , या दूसरी भाषा में कुछ भी कैसे कहें !

*_पांच मिनट के लिए, पहला साथी अपने अपने दूसरे साथी को अपने कौशल सिखाता है ! उसके बाद बदल लें *_दोनों साथी के जाने के बाद , एक बड़े समूह में एकत्र हो जाएं *\* कुछ जोड़ों से पूछें की वह संछेप में बताएं की उनके साथी ने उन्हें क्या सिखाया ! समझने में आसान और यादगार निर्देश  पर प्रतिबिंबित करने के लिए प्रोत्साहित करें।

![कार्रवाई में गतिविधि](http://mozilla.github.io/webmaker-curriculum/images/web-chef-01.jpg)

---

१ ० <बी आर >मिनट  
### बनाने की विधि लिखें

**अब एक रसोई की किताब में व्यंजनों की तरह कितने अच्छे निर्देश समझाएं ।** शेफ रेसिपी लिखते है दूसरे शेफ से साथ बाटने के लिए और खुद को याद दिलाने के लिए भी की कैसे करें !

उन सभी जोड़ों में , *_शिक्षार्थियों को आमंत्रित करें और उनसे संछेप में सरे कौशल सिखने के सरे स्टेप्स लिखें *_. एक-दूसरे के रेसिपी की समीक्षा करने के लिए जोड़े को प्रोत्साहित करें और *\* रेसिपी को  बेहतर बनाने के लिए *\* सकारात्मक प्रतिक्रिया दे!

![कार्रवाई में गतिविधि](http://mozilla.github.io/webmaker-curriculum/images/web-chef-02.jpg)

---

१ ० <बी आर> मिनट 
### अपनी सामग्री इकट्ठा करें

एक ऐसा नया सुजाव दें जिससे शेफ वेब का उपयोग करके अपनी रेसिपी अच्छी बना सकते हैं ! जीवन को अपने रेसिपी  में लाना होगा कि खुले तौर पर लाइसेंस सामग्री *\* खोजने के लिए वेब खोज करने के लिए जोड़े को आमंत्रित करें।

> आसानी से खुले तौर पर लाइसेंस प्राप्त सामग्री खोजने के लिए , इन सेवाओं का उपयोग करने का प्रयास करें:
> - [क्रिएटिव कॉमन्स खोज उपकरण](https://search.creativecommons.org/)
> - [गूगल उन्नत सेटिंग्स](http://www.google.com/advanced_search)
> - [विकिपीडिया](http://www.wikipedia.org/)
> - [फ़्लिकर](https://www.flickr.com/creativecommons)
> - [साउंडक्लाउड](https://soundcloud.com/search/sounds/?filter.license=to_share)

![कार्रवाई में गतिविधि](http://mozilla.github.io/webmaker-curriculum/images/web-chef-03.jpg)

समझाएं की शेफ **अपनी प्रेरणा स्वीकार करते हैं और अपना आरोपण दूसरों को देते हैं !. यही कारण है कि खुले तौर पर बांटने की संस्कृति का हिस्सा है।

[वेब शेफ नुस्खा टेम्पलेट का उपयोग करें](https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe), जोड़े को अपने नुस्खा के कदम अनुक्रम की और वेब की सामग्री विशेषता है। यदि आपके इंटरनेट की कनेक्टिविटी कम है तो पेन और कागज से अपनी रेसिपी को अतिरिक्त संसाधनो से जोड़ कर लिखें !

<a href="https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe"><img class="img-example" src="http://mozilla.github.io/webmaker-curriculum/images/web-chef-project.png" width="75%"></a>

**यदि समय अनुमति देता है और अपने शिक्षार्थियों को भी अपने स्वयं के वेब सामग्री बना सकते हैं ।** तस्वीरें लेने के लिए एक त्वरित वीडियो बनाने या नुस्खा के हिस्से के रूप में एक नया पाठ लिखने के बारे में सोचें ! बोनस में अपने शिक्षार्थियों वे वेब के लिए पोस्ट कर सकते हैं कुछ कर सकते हैं और आसानी से करने के लिए एक खुला लाइसेंस जोड़ने की फ्लिकर, विकिमीडिया कॉमन्स , साउंड क्लाउड  और यूट्यूब जैसी सेवाओं का उपयोग करते हुए , उनके मोबाइल फोन पर इन संसाधनों से बनाते हैं ।

<a href="https://laura.makes.org/thimble/MTczNjc1NTI=/web-chef-recipe"><img class="img-example" src="http://mozilla.github.io/webmaker-curriculum/images/web-chef-04.jpg"></a>

१ ० <बी आर >मिनट 
### वेब शेफ कुकिंग शो

**एक बड़े समूह में वापस सभी व्यंजनों और हर किसी को इकट्ठा करें *\* अब सभी वेब शेफ कुकिंग शो के लिए तैयार हैं! एक अन्य समूह से एक नुस्खा को पूरा करने के लिए शेफ  के दो जोड़े निरुपित करें ! **दो जोड़े सफलतापूर्वक सबसे तेजी से विधि का पालन कर सकते हैं।**

![कार्रवाई में वेब!](http://mozilla.github.io/webmaker-curriculum/images/web-chef-05.jpg)

*_यह अधिक चुनौतीपूर्ण बनाये *_ जोड़ों के होने पर ब्लाइंड फोल्डेड रेसिपी बनाये , और जबकि एक पैर पर होपिंग आदि !

कुछ राउंड के बाद, *\* अच्छे रेसिपी  *\* क्या बना देते है उससे दर्शाते हैं। अन्य जानकारी क्या मदद करेंगे? क्या यहाँ  के रूप में किसी को भी एक नुस्खा संशोधित किया है? यदि हां, तो क्यों और कैसे आप अन्य शेफ के साथ  संशोधन का हिस्सा हो सकता है?

[पोस्ट - गतिविधि प्रश्नावली ] को पूरा करें(http://goo.gl/forms/uOEzAbbH34), और अपने शिक्षार्थियों से उन्हें  [ पोस्ट- गतिविधि प्रश्नावली ] पूरा करने को कहें (http://goo.gl/forms/ZeyNYQzc1t).

**Comment by soapdog** [comment]
Thanks for the hard work on these activities! Your contribution is live at:

http://mozilla.github.io/mozilla-club-activity-web-chef/#hi

:smile_cat: 

I made some fixes to the Markdown Syntax and HTML tags that were translated by mistake. Please, if you can check that the live version is correct it would be great!

Thanks again!
