### ISSUE TITLE
Translation of aside.md into Swedish

### ISSUE THREAD

**Issue by bittin** [mozilla/mozilla-club-activity-web-chef#11]
#### Målgrupp
- 10+
- nybörjande instruktions designers
#### Material
- Pennor och papper
- Webbaserade enheter: mobil eller laptop
- (frivilligt) [Utskriven Web Chef recept mall](https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe)
#### Lärandemål
- Skriva öppet licensierat innehåll
- Använd konstruktiv kritik i en grupp eller runt om i närmiljön
- Skapa en webb resurs som guidar kamrater att slutföra en uppgift
#### Aktivitet i Action!

![Web Chef i action!](http://mozilla.github.io/webmaker-curriculum/images/chef-in-action.jpg)
Chloe Varelidi
P2PU ömsesidigt lärande med öppet innehåll i Berlin. 
#### See remixar från communityt

Se hur utbildare och aktivister har anpassat aktiviteten för sina specifika målgrupper i vårt. [Diskussionsforum](http://discourse.webmaker.org/t/testing-2-writing-the-web/1195/3).

**Comment by soapdog** [comment]
Wow!!! Another great work! Thanks a lot for this L10N :smile_cat: 

http://mozilla.github.io/mozilla-club-activity-web-chef/#sv
