### ISSUE TITLE
Translation of activity.md into Swedish

### ISSUE THREAD

**Issue by bittin** [mozilla/mozilla-club-activity-web-chef#12]
---

title: Web Chef
github: mozilla/mozilla-club-activity-web-chef
image: chef-man.jpg
competencies:
    - {label: "Open Practices", type: "open-practices"}
### Web Chef

Skapad av [Mozilla](https://webmaker.org/mentor), och inspirerad av [Creative Commons](https://creativecommons.org/) och [P2PU Skola för ömsesidigt lärande med öppet innehåll](https://p2pu.org/en/groups/teach-someone-something-with-open-content). 
## Studenterna kommer köra ett race genom att sekvensera pappers lådor märkta Med HTML taggar, **bli bekanta med dom mest vanliga HTML taggarna och hur man ska strukturera en webbsida**.

1-2 timmar
### Förberedelser

**Gör aktiviteten själv** för att bekanta dig med den.

[Skriv ut the Web Chef Recept mallen](https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe) åt dina studenter, om dom inte kommer ha tillgång till internet. 

**Genomför den [förberedande enkäten](http://goo.gl/forms/J1fsuwZEgs)**, och be dina studenter slutföra [deras förberedande enkät](http://goo.gl/forms/4DanIgrM9w). 

---

15<br>min
### Lär dig i Par

Börja session med att förklara att **alla har någonting dom kan lära sig och som den senare kan lära ut** och att förklara att **en av fördelarna med den öppna webben är att det är enkelt att dela din kunskap med andra**.

**Be studenterna att dela upp sig i par.** Bjud in studenterna att tänka en kort stund om **en simpel skill som dom kan dela med deras partner**. Några exempel kan inkludera: en ny dans, ett mycket bättre och snabbare sätt att knyta dina skor, eller hur man säger någonting på ett annat språk.

**I fem minuter, be den första eleven lär ut sin skill till klasskamraten i deras grupp dom fått sig till fördelad. Sen så byter dom av.** Efter båda klasskamraterna har gjort detta, be dom gå tillbaka till en stor grupp. Be några få par att kort förklara vad deras klasskamrat lärde dem. Encourage dem att reflektera på vad som gjorde instruktionerna enkla att förstå och att komma ihåg.

![aktivitet i action](http://mozilla.github.io/webmaker-curriculum/images/web-chef-01.jpg)

---

10<br>min
### Skriv ett recept

**Nu förklara hur bra instruktioner är som recept i en kokbok.** Kockar skriver recept för att dela med andra kockar och för att påminna dom själva om hur man lagar någonting. 

I samma par, **bjud in dina studenter att skriva en kort sammanfattning av stegen som krävs för att lära sig deras steg som krävs för att lära sig deras skill**. Uppmuntra paren att recensera varandras recept och att **ge konstruktiv kritik** för att göra varandras recept bättre.

![aktivitet i action](http://mozilla.github.io/webmaker-curriculum/images/web-chef-02.jpg)

---

10<br>min
### Samla dina ingredienser

Introducera ideén att kockar kan använda webben för att bättre illustrera deras recept. Bjud in paren till att  **söka på webben för att hitta öppet licenseriat innehåll** som skulle föra deras recept mer till liv.

> För att enkelt hitta öppet licenseriat innehål, prova att använda en av dessa tjänster:
> - [Creative Commons sök verktyg](https://search.creativecommons.org/)
> - [Google avancerade inställningar](http://www.google.com/advanced_search)
> - [Wikipedia](http://www.wikipedia.org/)
> - [Flickr](https://www.flickr.com/creativecommons)
> - [SoundCloud](https://soundcloud.com/search/sounds/?filter.license=to_share)

![aktivitet i action](http://mozilla.github.io/webmaker-curriculum/images/web-chef-03.jpg)

Förklara att kockar **erkänner deras inspiration och ger attribution till andra**. Det är en del av kulturen av att dela öppet.

[Använd Web Chef recept mallen](https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe), för att få paren att sekvensera deras recept steg och attribut the webb innehållet. Om du har dåligt med bandbredd, använd bara penna och papper för att skriva ditt recept och visa vilka ytterligare resurser som skulle kunna läggas till.

<a href="https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe"><img class="img-example" src="http://mozilla.github.io/webmaker-curriculum/images/web-chef-project.png" width="75%"></a>

**Om ni har tid över, förklara för dina studenter att dom också kan göra eget webb innehåll.** Tänk på att ta bilder, göra en snabb video eller skriva en ny text som en del av ditt recept. Bonus om dina studenter skapar dessa resurser på deras mobiltelefoner, använd tjänster som Flickr, Wikimedia Commons, SoundCloud och YouTube för att göra någonting som dom kan ladda upp till webben och enkelt lägga till en öppen licens till.

<a href="https://laura.makes.org/thimble/MTczNjc1NTI=/web-chef-recipe"><img class="img-example" src="http://mozilla.github.io/webmaker-curriculum/images/web-chef-04.jpg"></a>

---

10<br>min
### Web Chef matlagningsprogram

**Samla alla recepten och allihopa tillbaka till en stor grupp.** Nu är alla Webbkockarna redo för att eget matlagningsprogram! Be två par av kockar att slutföra ett recept från en annan grupp. **Dom två paren racar med varandra för att se vilka so kan slutföra dom andras recept snabbast.**

![Web Chef Action!](http://mozilla.github.io/webmaker-curriculum/images/web-chef-05.jpg)

**Gör det ännu svårare** genom att be paren slutföra recepten med ögonbindel, eller medans dom hoppar på ett ben, t.e.x.

Efter några rundor, **reflektera på vad som gör ett bra recept**. Vilken annan information skulle hjälpa? Har någon modifierat ett recept medans dom gjorde det? Om så är fallet, varför och hur kan dom dela med sig av den modiferingen med andra kockar?

Slutför [efter aktivitet frågeformuläret](http://goo.gl/forms/uOEzAbbH34), och be studenterna slutföra sitt [efter aktivitet frågeformulär](http://goo.gl/forms/ZeyNYQzc1t).

**Comment by soapdog** [comment]
Wow!!! Another great work! Thanks a lot for this L10N :smile_cat: 

http://mozilla.github.io/mozilla-club-activity-web-chef/#sv
