### ISSUE TITLE
Translation of activity.md into Bengali(bn-BD)

### ISSUE THREAD

**Issue by khalid32** [mozilla/mozilla-club-activity-web-chef#2]
---

title: Web Chef
github: mozilla/mozilla-club-activity-web-chef
image: chef-man.jpg
competencies:
    - {label: "Open Practices", type: "open-practices"}
### ওয়েবের শেফ

তৈরিকৃত [মজিলা](https://webmaker.org/mentor), এবং অনুপ্রাণিত [ক্রিয়েটিভ কোমনস](https://creativecommons.org/) এবং [P2PU স্কুল অফ ওপেন](https://p2pu.org/en/groups/teach-someone-something-

with-open-content)। 

শিক্ষার্থীরা প্রতিযোগিতা করবে HTML ট্যাগগুলো শ্রেণীবদ্ধকৃত পেপার বক্সে ক্রমে সাজানোর জন্য, **সবচেয়ে প্রচলিত HTML ট্যাগগুলোর সাথে পরিচিত হওয়া এবং কিভাবে একটি ওয়েব পেইজকে নির্মাণ করা হয়**।

১-২ ঘন্টা
### প্রস্তুতি

**কার্যকলাপ আপনি নিজে করুন** ইহার সাথে পরিচিত হওয়ার জন্য।

[ওয়েব শেফ রেসিপি টেমপ্লেটটি প্রিন্ট করুন](https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe) আপনার শিক্ষার্থীদের জন্য, যদি ওয়েবে আপনার প্রবেশাধিকার না থাকে।

**সম্পন্ন করুন [প্রাক-কার্যকলাপ প্রশ্নোত্তর](http://goo.gl/forms/J1fsuwZEgs)**, এবং আপনার শিক্ষার্থীদের সম্পন্ন করান [তাদের প্রাক-কার্যকলাপ প্রশ্নোত্তর](http://goo.gl/forms/4DanIgrM9w)। 

---

১৫<br>মিনিট
### জোড়ায় জোড়ায় শিখানো

সেশনটি শুরু করুন ব্যাখ্যা দিয়ে যে **সবারই কিছু না কিছু জানার ও শেখার আছে** এবং সেই **ওপেন ওয়েবের সুবিধাগুলোর মধ্যে একটি হচ্ছে এটা অন্যদের সাথে আপনার জ্ঞান শেয়ার করা সহজ**।

**শিক্ষার্থীদের যুগলে যোগ দিতে দিন।** আমন্ত্রণ করুন শিক্ষার্থীদের সংক্ষিপ্তভাবে চিন্তা করার ব্যাপারে **একটি সহজ দক্ষতা তারা তাদের পার্টনারের কাছে শেয়ার করতে পারে**। কিছু উদাহরণ হল: একটি নতুন নাচ, জুতার ফিতা বাধার আরও কার্যকর উপায়, অথবা কোনোকিছু আরেক 

ভাষায় কিভাবে বলবো।

**পাঁচ মিনিটের জন্য, প্রথম পার্টনার তাদের পার্টনারকে নিজেদের দক্ষতা শিখাবে। এরপর বদলাবে।** তারপর উভয় পার্টনার চলে যাওয়ার পর, তাদেরকে বড় গ্রুপে জমা করুন। কিছু যুগলকে জিজ্ঞাস করুন সংক্ষেপে বুঝানোর জন্য যে তাদের পার্টনার তাদের কি শিখিয়েছে। ভেবে দেখতে 

উৎসাহ দিন কোন নির্দেশাবলীর উপর সহজে বুঝতে ও মনে রাখতে পেরেছে ।

![কার্যকলাপের পদক্ষেপ](http://mozilla.github.io/webmaker-curriculum/images/web-chef-01.jpg)

---

১০<br>মিনিট
### একটি রেসিপি লিখুন

**এখন বুঝান কিভাবে রান্না বইয়ের রেসিপির মত ভাল নির্দেশাবলী করা হয়।** শেফরা রেসিপি লিখে অন্য শেফদের সাথে শেয়ার করার জন্য এবং আবার স্মরণ করিয়ে দেয় কিভাবে কোনকিছু বানানো যায় ।

একই যুগলকে, **আপনার শিক্ষার্থীদের দক্ষতা শিখার প্রয়োজনীয় পদক্ষেপগুলোর একটি সংক্ষিপ্ত রচনা লিখতে আমন্ত্রণ জানান**। যুগলকে একে অপরের রেসিপি পর্যালোচনা করার জন্য উৎসাহিত করুন এবং **গঠনমূলক ফিডব্যাক দিন** রেসিপিটা ভালভাবে বানানোর জন্য।

![কর্যকলাপের পদক্ষেপ](http://mozilla.github.io/webmaker-curriculum/images/web-chef-02.jpg)

---

১০<br>মিনিট
### আপনার উপাদানগুলো একত্র করুন

আইডিয়াটি উপস্থাপন করুন যা শেফরা ওয়েবকে ব্যবহার করতে পারে নিজেদের রেসিপিকে ভালভাবে বিচিত্র করার জন্য। যুগলকে আমন্ত্রণ করুন **ওয়েবকে সার্চ করতে যেন প্রকাশ্যভাবে লাইসেন্সপ্রাপ্ত বিষয়বস্তু খোঁজে** তা তাদের রেসিপিকে জীবন্ত করে তুলে।

> সহজে প্রকাশ্যভাবে লাইসেন্সপ্রাপ্ত বিষয়বস্তু পাওয়ার জন্য, চেষ্টা করুন এই সার্ভিসগুলো ব্যবহার করতে:
> - [সৃজনশীল সাধারন সার্চ টুল](https://search.creativecommons.org/)
> - [গুগল অ্যাডভান্স সেটিংস](http://www.google.com/advanced_search)
> - [উইকিপিডিয়া](http://www.wikipedia.org/)
> - [ফ্লিকার](https://www.flickr.com/creativecommons)
> - [সাউন্ডক্লাউড](https://soundcloud.com/search/sounds/?filter.license=to_share)

![কার্যকলাপের পদক্ষেপ](http://mozilla.github.io/webmaker-curriculum/images/web-chef-03.jpg)

ব্যাখ্যা করুন শেফরা **তাদের অনুপ্রেরণা স্বীকার করে এবং অন্যদের বিশেষণ দেয়**। এটাই প্রকাশ্যভাবে শেয়ার করা সংস্কৃতির অংশ।

[ওয়েব শেফ রেসিপির টেমপ্লেট ব্যবহার করুন](https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe),যেন যুগলরা তাদের রেসিপির ধাপগুলো বিন্যাস এবং ওরেবের বিষয়বস্তুর গুন রাখতে পারে। যদি আপনার নিম্ন-সংযোগ থাকে, 

তাহলে কলম ও কাগজ ব্যবহার করবেন রেসিপি লেখার জন্য এবং কি কি অতিরিক্ত উপায় যুক্ত করা যায় তা দেখান।

<a href="https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe"><img class="img-example" src="http://mozilla.github.io/webmaker-curriculum/images/web-chef-

project.png" width="75%"></a>

**যদি সময় থাকে, আপনার শিক্ষার্থীরা তাদের নিজেদের ওয়েবের বিষয়বস্তু তৈরি করতে পারে।** ছবি তোলা, কম সময়ে ভিডিও বানানো অথবা রেসিপির অংশ হিসেবে নতুন টেক্সট লেখা সম্পর্কে চিন্তা করুন। বোনাস হিসেবে যদি আপনার শিক্ষার্থীরা এই উপায়গুলো তাদের মোবাইল ফোন 

দিয়ে তৈরি করতে পারে, সার্ভিসগুলো যেমন ফ্লিকার, উইকিপিডিয়া কোমন্স, সাউন্ডক্লাউড এবং ইউটিউব  ব্যবহার করে যা ওয়েবে পোষ্ট করার জন্য তৈরি করতে পারে এবং সহজে একটি মুক্ত লাইসেন্স যুক্ত করতে পারে।

<a href="https://laura.makes.org/thimble/MTczNjc1NTI=/web-chef-recipe"><img class="img-example" src="http://mozilla.github.io/webmaker-curriculum/images/web-chef-

04.jpg"></a>

---

১০<br>মিনিট
### ওয়েব শেফ রান্নার শো

**সব রেসিপিগুলোকে এবং সবাইকে একটি বড় গ্রুপে একত্র করুন।** এখন সকল ওয়েব শেফরা তৈরি হয়ে আছে একটি রান্নার অনুষ্ঠানের জন্য! দুই যুগল শেফকে বরাদ্দ করুন আরেকটি গ্রুপের রেসিপি সম্পূর্ণ করার জন্য **দুই যুগল এক অপরের সাথে প্রতিযোগিতা লাগবে দেখানোর 

জন্য কারা সফলভাবে দ্রুত রেসিপি মেনে চলতে পারে।**

![ওয়েব শেফ অ্যাকশন!](http://mozilla.github.io/webmaker-curriculum/images/web-chef-05.jpg)

**ইহাকে আরও চ্যালেঞ্জীং করুন** যুগলকে চোখবাধা অবস্থায় সম্পূর্ণ করতে, অথবা এক পায়ে লাফানো অবস্থায়, ইত্যাদি।

কয়েকটি রাউন্ডের পর, **ভাল রেসিপির জন্য কি কি দরকার তা ভেবে দেখুন**। অন্যান্য তথ্য কি সাহায্য করবে? যখন তারা করেছে তখন কেউ রেসিপিকে বদলিয়েছে? যদি হয়, কেন এবং কিভাবে আপনি সেই পরিবর্তনকে অন্যান্য শেফদের কাছে শেয়ার করবেন?

সম্পূর্ণ করুন [পোস্ট-কার্যকলাপ প্রশ্নোত্তর](http://goo.gl/forms/uOEzAbbH34), এবং আপনার শিক্ষার্থীদেরও সম্পুর্ণ করান তাদের [পোস্ট-কার্যকলাপ প্রশ্নোত্তর](http://goo.gl/forms/ZeyNYQzc1t)।

**Comment by soapdog** [comment]
:smile_cat: thanks a lot for the awesome effort! We really appreciate it! This translation is now live at http://mozilla.github.io/mozilla-club-activity-web-chef/#bn
