### ISSUE TITLE
Translation of aside.md into Bengali(bn-BD)

### ISSUE THREAD

**Issue by khalid32** [mozilla/mozilla-club-activity-web-chef#3]
#### অডিয়েন্স
- ১০+
- শুরুর শিক্ষামূলক ডিজাইনার
#### উপকরণসমূহ
- কলম এবং কাগজ
- ওয়েব-সক্রিয় ডিভাইস: মোবাইল অথবা ল্যাপটপ
- (ঐচ্ছিক) [প্রিন্ট করা ওয়েব শেফ রেসিপি টেমপ্লেট](https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe)
#### শেখার উদ্দেশ্যসমূহ
- প্রকাশ্যভাবে লাইসেন্সপ্রাপ্ত বিষয়বস্তু আরোপ করা
- গ্রুপে অথবা কমিউনিটি সেটিং-এ গঠনমূলক সমালোচনা তৈরি করা
- ওয়েব সম্পদ বানানো যা পিয়ারকে একটি কাজ সম্পন্ন করতে পরিচালিত করে
#### কার্যকলাপের পদক্ষেপ!

![ওয়েব শেফ অ্যাকশন!](http://mozilla.github.io/webmaker-curriculum/images/chef-in-action.jpg)
ক্লোয়ি ভ্যারালিডি
P2PU পিয়ার বার্লিনে খোলা বিষয়বস্তুর সাথে শেখা। 

কমিউনিটির রিমিক্সসমূহ দেখুন

দেখুন শিক্ষাবিদ এবং অ্যাকটিভিস্টরা এই কার্যকলাপ পরিবর্তিত করেছে তাদের সুনির্দিষ্ট অডিয়েন্সের জন্য আমাদের [ডিসকাশন ফরামে](http://discourse.webmaker.org/t/testing-2-writing-the-web/1195/3)।

**Comment by soapdog** [comment]
:smile_cat: thanks a lot for the awesome effort! We really appreciate it! This translation is now live at http://mozilla.github.io/mozilla-club-activity-web-chef/#bn

**Comment by ldecoursy** [comment]
woohoo!  @soapdog I just noticed the formatting on the fourth hyperlink is a little wonky so it's leading to an error.

**Comment by soapdog** [comment]
@ldecoursy fixed the link! Thanks for spotting this out.
