### ISSUE TITLE
Correction localization of aside.md to Bengali (bd)

### ISSUE THREAD

**Issue by mijanurrahman** [mozilla/mozilla-club-activity-web-chef#4]
#### শ্রোতৃমণ্ডলী
- ১০+
- প্রারম্ভের শিক্ষামূলক ডিজাইনার
#### উপকরণসমূহ
- কলম এবং কাগজ
- ওয়েব-সক্রিয় ডিভাইস: মোবাইল অথবা ল্যাপটপ
- (ঐচ্ছিক) [প্রিন্ট করা ওয়েব শেফ রেসিপি টেমপ্লেট](https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe)
#### শেখার উদ্দেশ্যসমূহ
- প্রকাশ্যভাবে লাইসেন্সপ্রাপ্ত বিষয়বস্তু আরোপ করা
- গ্রুপে অথবা কমিউনিটি সেটিং-এ গঠনমূলক সমালোচনা তৈরি করা
- ওয়েব সম্পদ বানানো যা পিয়ারকে একটি কাজ সম্পন্ন করতে পরিচালিত করে
#### কার্যকলাপের পদক্ষেপ!

![ওয়েব শেফ অ্যাকশন!](http://mozilla.github.io/webmaker-curriculum/images/chef-in-action.jpg)
ক্লোয়ি ভ্যারালিডি
P2PU পিয়ার বার্লিনে খোলা বিষয়বস্তুর সাথে শেখা। 

কমিউনিটির রিমিক্সসমূহ দেখুন

দেখুন কিভাবে শিক্ষাবিদ ও কর্মীরা এই কার্যকলাপকে কোন নির্দিষ্ট দর্শকের জন্য রিমিক্স করেছে [আলোচনা ফোরামে](http://discourse.webmaker.org/t/testing-2-writing-the-web/1195/3)।

**Comment by ldecoursy** [comment]
@mijanurrahman Can you say more about what you corrected from the previous version? Also, feel free to add new images (with proper attribution) if you have them :)

**Comment by mijanurrahman** [comment]
@ldecoursy  I corrected some word meaning
অডিয়েন্স >>> শ্রোতৃমণ্ডলী

দেখুন শিক্ষাবিদ এবং অ্যাকটিভিস্টরা এই কার্যকলাপ পরিবর্তিত করেছে তাদের সুনির্দিষ্ট অডিয়েন্সের জন্য আমাদের ডিসকাশন ফরামে >>> দেখুন কিভাবে শিক্ষাবিদ ও কর্মীরা এই কার্যকলাপকে কোন নির্দিষ্ট দর্শকের জন্য রিমিক্স করেছে আলোচনা ফোরামে

**Comment by soapdog** [comment]
তোমাকে ধন্যবাদ

Thanks a lot for the correction :+1: I've pushed this to the live version. Please keep sending them if you see something that can be improved (remember to add a brief description of the fixes in a comment too if possible)
