### ISSUE TITLE
Translation of activity.md into German

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/mozilla-club-activity-web-chef#6]
---

title: Web Chef
github: mozilla/mozilla-club-activity-web-chef
image: chef-man.jpg
competencies:
- {label: "Open Practices", type: "open-practices"}
### Web Chef

Produziert von [Mozilla](https://webmaker.org/mentor) und inspiriert von [Creative Commons](https://creativecommons.org/) und [P2PU School of Open](https://p2pu.org/en/groups/teach-someone-something-with-open-content).

Die Lernenden werden darum wetteifern, die Papier-Boxen mit HTML-Tags zu beschriften, **um so mit den geläufigsten HTML-Tags und der Struktur einer Web-Seite vertraut zu werden**.

1-2 Stunden
### Vorbereitung

**Absolviere die Übung selber**, um dich damit vertraut zu machen.

[Drucke die Web-Kochrezept-Vorlagen](https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe) für die Lernenden aus, falls du offline arbeiten musst.

**Beantworte den [Vorbereitungs-Fragebogen](http://goo.gl/forms/J1fsuwZEgs)** und lass die Lernenden [ihren Vorbereitungs-Fragebogen](http://goo.gl/forms/4DanIgrM9w) ausfüllen.

---

15<br>min
### Lernen in Paaren

Beginn die Sitzung damit, dass du erläuterst, dass **jeder etwas zu lernen und etwas beizubringen hat** und dass **ein Vorzug des Offenen Webs darin liegt, dass es leicht ist, sein Wissen mit anderen zu teilen**.

**Lass sich die Lernenden in Paaren zusammenfinden.** Lade sie dazu ein, kurz über **eine kleine Fertigkeit nachzudenken, die sie mit ihrem Partner teilen können**. Ein paar Beispiele: einen neuen Tanz, eine effizientere Art, sich die Schuhe zu binden oder wie man etwas in einer anderen Sprache sagt.

**Fünf Minuten lang bringt einer dem anderen das bei. Danach wird getauscht.** Nachdem beide Partner fertig sind, findet euch in einer großen Gruppe zurück. Frage einige Paare, kurz zu erklären, was sie gelernt haben. Ermutige sie dazu, darüber nachzudenken, was die Anweisungen leicht verständlich und gut zum Merken gemacht hat.

![Aktivität bei der Arbeit](http://mozilla.github.io/webmaker-curriculum/images/web-chef-01.jpg)

---

10<br>min
### Schreib ein Rezept

**Jetzt erkläre, dass gute Anleitungen wie Rezepte in einem Kochbuch sind.** Köche schreiben Rezepte, um sie mit anderen Köchen zu teilen und auch, um sich selber daran zu erinnern, wie etwas gemacht wird.

In den selben Gruppen, **lass die Lernenden eine kurze Zusammenfassung schreiben, welche Schritte notwendig sind, um die Fertigkeit zu lernen**. Ermutige die Paare, das Rezept des anderen durchzulesen und **konstruktives Feedback zu geben**, wie es noch besser geschrieben werden kann.

![Aktivität bei der Arbeit](http://mozilla.github.io/webmaker-curriculum/images/web-chef-02.jpg)

---

10<br>min
### Trage die Zutaten zusammen

Stell die Idee vor, dass Köche das Web dazu benutzen können, ihre Rezepte besser darzustellen. Lade die Paare ein, **das Web nach offen lizensierten Inhalten zu durchsuchen**, die ihre Rezepte mit Leben füllen würden.

> Um leicht offen lizensierte Inhalte zu finden, probiere einen dieser Dienste:
> - [Creative Commons Suche](https://search.creativecommons.org/)
> - [Google Erweiterte Suche](http://www.google.com/advanced_search)
> - [Wikipedia](http://www.wikipedia.org/)
> - [Flickr](https://www.flickr.com/creativecommons)
> - [SoundCloud](https://soundcloud.com/search/sounds/?filter.license=to_share)

![Aktivität bei der Arbeit](http://mozilla.github.io/webmaker-curriculum/images/web-chef-03.jpg)

Erläutere, dass Köche **ihre Inspirationsquellen würdigen und sie benennen**. Das gehört zur Kultur des offenen Teilens dazu.

[Benutze die Web-Kochrezept-Vorlage](https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe), damit die Paare die Schritte ihres Rezeptes aufzählen und auf Web-Inhalte verweisen. Falls du wenig Bandbreite hast, benutz Stift und Papier, um die Rezepte aufzuschreiben und zeige, welche zusätzlichen Inhalte hinzugefügt werden würden.

<a href="https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe"><img class="img-example" src="http://mozilla.github.io/webmaker-curriculum/images/web-chef-project.png" width="75%"></a>

**Falls es die Zeit zulässt, können die Lernenden auch ihre eigenen Web-Inhalte erstellen.** Beispielsweise durch Fotos, einem kurzen Video oder einem neuen Text als Teil des Rezeptes. Bonuspunkte, falls die Lernenden diese Inhalte mit ihren Smartphones erstellen und dabei Dienste wie Flickr, Wikimedia Commons, SoundCloud und YouTube verwenden und etwas schaffen, dass sie in's Web stellen können und ihm eine offene Lizenz zuweisen.

<a href="https://laura.makes.org/thimble/MTczNjc1NTI=/web-chef-recipe"><img class="img-example" src="http://mozilla.github.io/webmaker-curriculum/images/web-chef-04.jpg"></a>

---

10<br>min
### Web Kochshow

**Sammle alle Rezepte ein und bring sie alle in die große Gruppe zurück.** Jetzt sind alle Köche bereit für eine Kochshow! Weise zwei Koch-Paaren die Aufgabe zu, das Rezept einer anderen Gruppe auszuführen. **Die beiden Gruppen veranstalten dabei ein Wettrennen, um zu sehen, wer das Rezept am schnellsten erfolgreich umgesetzt bekommt.**

![Web Koch-Aktion!](http://mozilla.github.io/webmaker-curriculum/images/web-chef-05.jpg)

**Steigere die Herausforderung** dadurch, dass sie die Rezepte blind erledigen müssen oder indem sie dabei auf einem Bein springen etc.

Nach ein paar Runden **überlegt zusammen, was ein gutes Rezept ausmacht**. Welche anderen Informationen würden helfen? Hat jemand ein Rezept bereits so abgewandelt? Falls dem so ist, warum und wie könnten die Änderungen mit den anderen Köchen geteilt werden?

Beantworte den [Nachbereitungs-Fragebogen](http://goo.gl/forms/uOEzAbbH34) und lass die Lernenden ihren eigenen [Nachbereitungs-Fragebogen](http://goo.gl/forms/ZeyNYQzc1t) ausfüllen.

**Comment by soapdog** [comment]
Thanks again for the amazing work! You rock! :smile_cat: 

check out your L10N at http://mozilla.github.io/mozilla-club-activity-web-chef/#de
