### ISSUE TITLE
Translation of aside.md into German

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/mozilla-club-activity-web-chef#7]
#### Publikum
- 10+
- Anfänger im lehrreichen Denken
#### Material
- Stift und Papier
- Web-fähige Geräte: Smartphones oder Laptop
- (optional) [Ausgedrucke Web-Kochrezept-Vorlage](https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe)
#### Lernziele
- Auf offen lizensierte Inhalte verweisen
- Konstruktive Kritik in einer Gruppe oder einer Gemeinschaft üben
- Eine Web-Anleitung erstellen, die anderen dabei hilft, eine Aufgabe zu erfüllen
#### Aktivität bei der Arbeit!

![Web-Köche bei der Arbeit!](http://mozilla.github.io/webmaker-curriculum/images/chef-in-action.jpg)
Chloe Varelidi
P2PU Gruppen-Lernen mit offenen Inhalten in Berlin. 

Weitere Community-Remixes
Siehe auch weitere Wege in unserem [Diskussions-Forum](http://discourse.webmaker.org/t/testing-2-writing-the-web/1195/3), wie Lehrende und Aktivisten diese Aktivität für ihr Publikum abgewandelt haben.

**Comment by soapdog** [comment]
Thanks again for the amazing work! You rock! :smile_cat: 

check out your L10N at http://mozilla.github.io/mozilla-club-activity-web-chef/#de
