### ISSUE TITLE
Localization of aside.md into Hindi

### ISSUE THREAD

**Issue by join2ashish** [mozilla/mozilla-club-activity-web-chef#8]
#### दर्शक
-  ८ +
-  प्रणाली विचारकों से शुरुआत
#### सामग्री
- कलम और कागज
- वेब सक्षम उपकरण : मोबाइल या लैपटॉप
- (इच्छानुसार) [मुद्रित वेब रुपकार के विधि का साँचा](https://michelle.makes.org/thimble/OTg5MDY5NTY4/web-chef-recipe)
#### सीखने का  मकसद
- खुले तौर पर लाइसेंस सामग्री गुण
- एक समूह या समुदाय की स्थापना में रचनात्मक आलोचना का प्रयोग करें
- एक वेब संसाधन बनाएँ जिससे एक कार्य को पूरा करने के लिए साथियों को गाइड मिले 
#### गतिविधि में कार्रवाई करें !

![वेब रुपकार कार्रवाई में !](http://mozilla.github.io/webmaker-curriculum/images/chef-in-action.jpg)
क्लो वरेलीडी 
पी २ पी यु  बर्लिन में खुली सामग्री के साथ सीखने वाले सहकर्मी।
#### समुदाय रीमिक्स देखें

हमारे [ चर्चा मंच ] में शिक्षकों और कार्यकर्ताओं को उनकी विशिष्ट दर्शकों के लिए इस गतिविधि को संशोधित किया है तरीकों की जाँच करें(http://discourse.webmaker.org/t/testing-2-writing-the-web/1195/3).

**Comment by soapdog** [comment]
Thanks for the hard work on these activities! Your contribution is live at:

http://mozilla.github.io/mozilla-club-activity-web-chef/#hi

:smile_cat: 

I made some fixes to the Markdown Syntax and HTML tags that were translated by mistake. Please, if you can check that the live version is correct it would be great!

Thanks again!
